### ISSUE TITLE
ValueError: zero-size array to reduction operation maximum which has no identity

### ISSUE THREAD

**Issue by shellvon** [mknicklee/image-inpainting#2]
Hello:

When I use my own mask.bmp(Created by Photoshop).I meet some problems:
`➜  image-inpainting git:(master) ✗  file masks/my_mask.bmp`
> masks/my_mask.bmp: PC bitmap, Windows 3.x format, 420 x 420 x 8

```python
Traceback (most recent call last):
  File "t.py", line 7, in <module>
    inpaint('images/my.jpg','masks/my_mask.bmp')
  File "inpainting.pyx", line 400, in inpainting.inpaint (inpainting.c:8042)
    cpdef inpaint(src_im, mask_im,
  File "inpainting.pyx", line 449, in inpainting.inpaint (inpainting.c:6799)
    unfilled_img[np.where(mask == 0.0)] = [0.0, 0.9999, 0.0]
ValueError: shape mismatch: value array of shape (3,) could not be broadcast to indexing result of shape (130422,)
```

So i use **iMageMagick** to convert bmp to pgm. but i still meet some problems. i have no idea what to do.
```python
Traceback (most recent call last):
  File "t.py", line 7, in <module>
    inpaint('images/my.jpg','my_mask.pgm')
  File "inpainting.pyx", line 400, in inpainting.inpaint (inpainting.c:8042)
    cpdef inpaint(src_im, mask_im,
  File "inpainting.pyx", line 474, in inpainting.inpaint (inpainting.c:7408)
    highest_priority = find_max_priority(boundary_ptx,
  File "inpainting.pyx", line 190, in inpainting.find_max_priority (inpainting.c:2968)
    int xx = np.where(grad_patch == np.max(grad_patch))[0][0]
  File "/usr/local/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 2252, in amax
    out=out, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/numpy/core/_methods.py", line 26, in _amax
    return umr_maximum(a, axis, None, out, keepdims)


ValueError: zero-size array to reduction operation maximum which has no identity
```

Here is my code:
```python
from inpainting import inpaint
inpaint('images/my.jpg','my_mask.pgm')
```
attachment is my image resource(
[归档.zip](https://github.com/mknicklee/image-inpainting/files/751973/default.zip)
)

**Comment by nlee737** [comment]
Hi shellvon,

The error you received was due to the algorithm trying to grab a "patch" that goes beyond the image's borders due to the region to remove in the mask being too close to the borders. I added padding to the image and mask before it gets passed when calling the inpaint function. I haven't explored your error with the bitmap mask but it should work with the pgm mask now.

**Comment by shellvon** [comment]
@mknicklee, thank you for your detailed explanation~ I will try again.😁
