### ISSUE TITLE
Cannot convert str to numpy.ndarray (save_name)

### ISSUE THREAD

**Issue by kubmin** [mknicklee/image-inpainting#5]
Hi there. Wonderfull project! However, I'm running into an error while inpainting.

Without image name
```
>>> inpaint('/home/server/python/image-inpainting/images/baby.jpg', '/home/server/python/image-inpainting/masks/baby-mask.bmp')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "inpainting.pyx", line 400, in inpainting.inpaint (inpainting.c:8928)
    cpdef inpaint(src_im, mask_im, save_name,
TypeError: inpaint() takes at least 3 positional arguments (2 given)

```
With image name
```
>>> inpaint('images/baby.jpg','masks/baby-mask.bmp','baby', gaussian_blur=0, gaussian_sigma=1, patch_size=10)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "inpainting.pyx", line 400, in inpainting.inpaint (inpainting.c:8952)
    cpdef inpaint(src_im, mask_im, save_name,
  File "inpainting.pyx", line 428, in inpainting.inpaint (inpainting.c:7080)
    save_name = save_name[:dot] + '-inpainted.jpg'
TypeError: Cannot convert str to numpy.ndarray
```

My code:

```
from inpainting import inpaint
inpaint('images/baby.jpg','masks/baby-mask.bmp', 'baby')
```

This error doesn't seem to be happening when I'm using the GUI, but I would love to be able to use the package without having to use the GUI.

Any ideas ?
Thanks!

**Comment by zohaibn** [comment]
Hi,

Can you tell me how did you manage to run the software? I keep on getting a dlopen error when it imports the .so file.

Thanks
